---
kind: pipeline
type: docker
name: Java maven testing

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: settings
    image: md5lukas/drone-mvn-settings
    settings:
      servers:
        - id: woolgens-network
          username: woolgens-default
      serverSecrets:
        from_secret: WOOLGENS_NEXUS_CREDENTIALS
  - name: test
    image: maven
    depends_on: [settings, mongo]
    commands:
      - mvn -U test -s settings.xml

services:
  - name: mongo
    image: mongo:4
    ports:
      - 27017


---
kind: pipeline
type: docker
name: Java maven testing and server deployment

environment:
  SERVICE_NAME: user

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: settings
    image: md5lukas/drone-mvn-settings
    settings:
      servers:
        - id: woolgens
          username: woolgens
      serverSecrets:
        from_secret: WOOLGENS_NEXUS_CREDENTIALS
  - name: install
    image: maven
    depends_on: [settings, mongo]
    commands:
      - mvn -U package -s settings.xml
  - name: delete
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: WOOLGENS_SERVER_HOST
      port:
        from_secret: WOOLGENS_SERVER_PORT
      username:
        from_secret: WOOLGENS_SERVER_USER
      password:
        from_secret: WOOLGENS_SERVER_PASSWORD
      script:
        - export SERVICE_NAME=$SERVICE_NAME
        - echo $${SERVICE_NAME}
        - echo $SERVICE_NAME
        - echo $$SERVICE_NAME
        - rm -R /home/services/$${SERVICE_NAME}-service/
        - cp /home/services/template/ /home/services/$${SERVICE_NAME}-service/
  - name: deploy
    depends_on: [install, delete]
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: WOOLGENS_SERVER_HOST
      port:
        from_secret: WOOLGENS_SERVER_PORT
      username:
        from_secret: WOOLGENS_SERVER_USER
      password:
        from_secret: WOOLGENS_SERVER_PASSWORD
      target: /home/services/$$SERVICE_NAME-service/app/
      source: target/quarkus-app/*
      strip_components: 2
  - name: start
    depends_on: [deploy]
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: WOOLGENS_SERVER_HOST
      port:
        from_secret: WOOLGENS_SERVER_PORT
      username:
        from_secret: WOOLGENS_SERVER_USER
      password:
        from_secret: WOOLGENS_SERVER_PASSWORD
      script:
        - export SERVICE_NAME=$SERVICE_NAME
        - cd /home/services/$$SERVICE_NAME-service/
        - docker-compose down
        - SERVICE_NAME=$${SERVICE_NAME} docker-compose up -d --build

services:
  - name: mongo
    image: mongo:4
    ports:
      - 27017
